services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_python_backend
    restart: always
    ports:
      - "8081:8081"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_vue_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend