services:
  backend:
    image: ${BACKEND_IMAGE:-rulescope-backend}:${TAG:-latest}
    container_name: rulescope_backend
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE:-rulescope-frontend}:${TAG:-latest}
    container_name: rulescope_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
